//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intertexti.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Intertexti.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;MycroXaml Name=&quot;Form&quot;
        ///  xmlns:wf=&quot;System.Windows.Forms, System.Windows.Forms, Version=1.0.5000.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&quot;
        ///  xmlns:ixa=&quot;Intertexti.Actions, Intertexti&quot;
        ///  xmlns:ixc=&quot;Intertexti.Controllers, Intertexti&quot;
        ///  xmlns:ixv=&quot;Intertexti.Views, Intertexti&quot;
        ///  xmlns:ixm=&quot;Intertexti.Models, Intertexti&quot;
        ///  xmlns:wfui=&quot;WeifenLuo.WinFormsUI.Docking, WeifenLuo.WinFormsUI.Docking&quot;
        ///  xmlns:def=&quot;def&quot;
        ///  xmlns:ref=&quot;ref&quot;&gt;
        ///  &lt;wf:Form Text=&quot;Abou [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;MycroXaml Name=&quot;Form&quot;
        ///  xmlns:wf=&quot;System.Windows.Forms, System.Windows.Forms, Version=1.0.5000.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&quot;
        ///  xmlns:ix=&quot;Intertexti, Intertexti&quot;
        ///  xmlns:ixdx=&quot;Intertexti.DevExpressControls, Intertexti&quot;
        ///  xmlns:ixc=&quot;Intertexti.Controllers, Intertexti&quot;
        ///  xmlns:ixv=&quot;Intertexti.Views, Intertexti&quot;
        ///  xmlns:def=&quot;def&quot;
        ///  xmlns:ref=&quot;ref&quot;&gt;
        ///  &lt;ix:GenericPane ref:Name=&quot;Container&quot;
        ///    TabText=&quot;All Notecards&quot;
        ///    ClientSize=&quot;400, 19 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string allNotecards {
            get {
                return ResourceManager.GetString("allNotecards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;!--DockPanel configuration file. Author: Weifen Luo, all rights reserved.--&gt;
        ///&lt;!--!!! AUTOMATICALLY GENERATED FILE. DO NOT MODIFY !!!--&gt;
        ///&lt;DockPanel FormatVersion=&quot;1.0&quot; DockLeftPortion=&quot;0.25&quot; DockRightPortion=&quot;0.25&quot; DockTopPortion=&quot;0.25&quot; DockBottomPortion=&quot;0.25&quot; ActiveDocumentPane=&quot;-1&quot; ActivePane=&quot;-1&quot;&gt;
        ///  &lt;Contents Count=&quot;5&quot;&gt;
        ///    &lt;Content ID=&quot;0&quot; PersistString=&quot;Intertexti.GenericPane,tableOfContentsPane.xml&quot; AutoHidePortion=&quot;0.25&quot; IsHidden=&quot;False&quot; IsFloat=&quot;False&quot; Ta [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string defaultLayout {
            get {
                return ResourceManager.GetString("defaultLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;MycroXaml Name=&quot;Form&quot;
        ///  xmlns:wf=&quot;System.Windows.Forms, System.Windows.Forms, Version=1.0.5000.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&quot;
        ///  xmlns:ixa=&quot;Intertexti.Actions, Intertexti&quot;
        ///  xmlns:ixc=&quot;Intertexti.Controllers, Intertexti&quot;
        ///  xmlns:ixv=&quot;Intertexti.Views, Intertexti&quot;
        ///  xmlns:ixm=&quot;Intertexti.Models, Intertexti&quot;
        ///  xmlns:wfui=&quot;WeifenLuo.WinFormsUI.Docking, WeifenLuo.WinFormsUI.Docking&quot;
        ///  xmlns:ixdx=&quot;Intertexti.DevExpressControls, Intertexti&quot;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string find {
            get {
                return ResourceManager.GetString("find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;MycroXaml Name=&quot;Form&quot;
        ///  xmlns:wf=&quot;System.Windows.Forms, System.Windows.Forms, Version=1.0.5000.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&quot;
        ///  xmlns:ix=&quot;Intertexti, Intertexti&quot;
        ///  xmlns:ixdx=&quot;Intertexti.DevExpressControls, Intertexti&quot;
        ///  xmlns:ixc=&quot;Intertexti.Controllers, Intertexti&quot;
        ///  xmlns:ixv=&quot;Intertexti.Views, Intertexti&quot;
        ///  xmlns:def=&quot;def&quot;
        ///  xmlns:ref=&quot;ref&quot;&gt;
        ///  &lt;ix:GenericPane ref:Name=&quot;Container&quot;
        ///    TabText=&quot;Index&quot;
        ///    ClientSize=&quot;400, 190&quot;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string indexPane {
            get {
                return ResourceManager.GetString("indexPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon intertexti {
            get {
                object obj = ResourceManager.GetObject("intertexti", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;MycroXaml Name=&quot;Form&quot;
        ///  xmlns:wf=&quot;System.Windows.Forms, System.Windows.Forms, Version=1.0.5000.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&quot;
        ///  xmlns:ix=&quot;Intertexti, Intertexti&quot;
        ///  xmlns:ixc=&quot;Intertexti.Controllers, Intertexti&quot;
        ///  xmlns:ixdx=&quot;Intertexti.DevExpressControls, Intertexti&quot;
        ///  xmlns:ixv=&quot;Intertexti.Views, Intertexti&quot;
        ///  xmlns:def=&quot;def&quot;
        ///  xmlns:ref=&quot;ref&quot;&gt;
        ///  &lt;ix:GenericPane ref:Name=&quot;Container&quot;
        ///    TabText=&quot;References&quot;
        ///    ClientSize=&quot;400, 190&quot;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string linksToPane {
            get {
                return ResourceManager.GetString("linksToPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;MycroXaml Name=&quot;Form&quot;
        ///  xmlns:wf=&quot;System.Windows.Forms, System.Windows.Forms, Version=1.0.5000.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&quot;
        ///  xmlns:ixa=&quot;Intertexti.Actions, Intertexti&quot;
        ///  xmlns:ixc=&quot;Intertexti.Controllers, Intertexti&quot;
        ///  xmlns:ixv=&quot;Intertexti.Views, Intertexti&quot;
        ///  xmlns:ixm=&quot;Intertexti.Models, Intertexti&quot;
        ///  xmlns:wfui=&quot;WeifenLuo.WinFormsUI.Docking, WeifenLuo.WinFormsUI.Docking&quot;
        ///  xmlns:def=&quot;def&quot;
        ///  xmlns:ref=&quot;ref&quot;&gt;
        ///  &lt;ixv:ApplicationFor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mainform {
            get {
                return ResourceManager.GetString("mainform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;MycroXaml Name=&quot;Form&quot;
        ///  xmlns:wf=&quot;System.Windows.Forms, System.Windows.Forms, Version=1.0.5000.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&quot;
        ///  xmlns:ix=&quot;Intertexti, Intertexti&quot;
        ///  xmlns:ixdx=&quot;Intertexti.DevExpressControls, Intertexti&quot;
        ///  xmlns:ixctrl=&quot;Intertexti.Controls, Intertexti&quot;
        ///  xmlns:ixc=&quot;Intertexti.Controllers, Intertexti&quot;
        ///  xmlns:ixv=&quot;Intertexti.Views, Intertexti&quot;
        ///  xmlns:def=&quot;def&quot;
        ///  xmlns:ref=&quot;ref&quot;&gt;
        ///  &lt;ix:GenericPane ref:Name=&quot;Container&quot;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string metadataPane {
            get {
                return ResourceManager.GetString("metadataPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;MycroXaml Name=&quot;Form&quot;
        ///  xmlns:wf=&quot;System.Windows.Forms, System.Windows.Forms, Version=1.0.5000.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&quot;
        ///  xmlns:ixc=&quot;Intertexti.Controllers, Intertexti&quot;
        ///  xmlns:ixv=&quot;Intertexti.Views, Intertexti&quot;
        ///  xmlns:ix=&quot;Intertexti, Intertexti&quot;
        ///  xmlns:ixa=&quot;Intertexti.Actions, Intertexti&quot;
        ///  xmlns:wk=&quot;WebKit, OpenWebKitSharp&quot;
        ///  xmlns:editor=&quot;MSDN.Html.Editor, MSDN.HtmlEditorControl, Version=2.0.4779.28314, Culture=neutral, Public [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string notecard {
            get {
                return ResourceManager.GetString("notecard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;MycroXaml Name=&quot;Form&quot;
        ///  xmlns:wf=&quot;System.Windows.Forms, System.Windows.Forms, Version=1.0.5000.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&quot;
        ///  xmlns:ix=&quot;Intertexti, Intertexti&quot;
        ///  xmlns:ixdx=&quot;Intertexti.DevExpressControls, Intertexti&quot;
        ///  xmlns:ixc=&quot;Intertexti.Controllers, Intertexti&quot;
        ///  xmlns:ixv=&quot;Intertexti.Views, Intertexti&quot;
        ///  xmlns:def=&quot;def&quot;
        ///  xmlns:ref=&quot;ref&quot;&gt;
        ///  &lt;ix:GenericPane ref:Name=&quot;Container&quot;
        ///    TabText=&quot;Orphan Notecards&quot;
        ///    ClientSize=&quot;400, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string orphanNotecards {
            get {
                return ResourceManager.GetString("orphanNotecards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;MycroXaml Name=&quot;Form&quot;
        ///  xmlns:wf=&quot;System.Windows.Forms, System.Windows.Forms, Version=1.0.5000.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&quot;
        ///  xmlns:ix=&quot;Intertexti, Intertexti&quot;
        ///  xmlns:ixc=&quot;Intertexti.Controllers, Intertexti&quot;
        ///  xmlns:ixdx=&quot;Intertexti.DevExpressControls, Intertexti&quot;
        ///  xmlns:ixv=&quot;Intertexti.Views, Intertexti&quot;
        ///  xmlns:def=&quot;def&quot;
        ///  xmlns:ref=&quot;ref&quot;&gt;
        ///  &lt;ix:GenericPane ref:Name=&quot;Container&quot;
        ///    TabText=&quot;Referenced By&quot;
        ///    ClientSize=&quot;400, 19 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string referencedByPane {
            get {
                return ResourceManager.GetString("referencedByPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;MycroXaml Name=&quot;Schema&quot;
        ///  xmlns:d=&quot;System.Data, System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&quot;
        ///  xmlns:def=&quot;def&quot;
        ///  xmlns:ref=&quot;ref&quot;&gt;
        ///  &lt;d:DataSet Name=&quot;Dataset&quot;&gt;
        ///    &lt;d:Tables&gt;
        ///      &lt;d:DataTable Name=&quot;Notecards&quot; TableName=&quot;Notecards&quot;&gt;
        ///        &lt;d:Columns&gt;
        ///          &lt;d:DataColumn Name=&quot;NotecardID&quot; ColumnName=&quot;ID&quot; AllowDBNull=&quot;false&quot; AutoIncrement=&quot;true&quot; DataType=&quot;System.Int32&quot; /&gt;
        ///          &lt;d:DataColumn ColumnName=&quot;TableOfCont [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string schema {
            get {
                return ResourceManager.GetString("schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;MycroXaml Name=&quot;Form&quot;
        ///  xmlns:wf=&quot;System.Windows.Forms, System.Windows.Forms, Version=1.0.5000.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&quot;
        ///  xmlns:ix=&quot;Intertexti, Intertexti&quot;
        ///  xmlns:ixdx=&quot;Intertexti.DevExpressControls, Intertexti&quot;
        ///  xmlns:ixc=&quot;Intertexti.Controllers, Intertexti&quot;
        ///  xmlns:ixv=&quot;Intertexti.Views, Intertexti&quot;
        ///  xmlns:ixa=&quot;Intertexti.Actions, Intertexti&quot;
        ///  xmlns:def=&quot;def&quot;
        ///  xmlns:ref=&quot;ref&quot;&gt;
        ///  &lt;ix:GenericPane ref:Name=&quot;Container&quot;
        ///    Ta [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tableOfContentsPane {
            get {
                return ResourceManager.GetString("tableOfContentsPane", resourceCulture);
            }
        }
    }
}
